apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: kube-green
  labels:
    app: users
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: users
