kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-green-admin-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kube-green-admin
  namespace: kube-green
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""