apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-green-nfs
  namespace: kube-green
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.7.242.140
    path: "/nfs_share"
