apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-green-nfs
  namespace: kube-green
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi

