apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T17:58:13Z"
  name: accounts-config
  namespace: kube-green
  resourceVersion: "19400"
  uid: 0cbd2ac8-97a6-45ff-9bd0-3fa61e22ec32
data:
  kube.land.config.accounts.message: "Best State is Myth"
