apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T17:58:13Z"
  name: kube-ora-config
  namespace: kube-green
  resourceVersion: "19400"
  uid: 0cbd2ac8-97a6-45ff-9bd0-3fa61e22ec32
data:
  spring.datasource.jta.enabled: "true"
  spring.datasource.tomcat.driver-class-name: oracle.jdbc.driver.OracleDriver
  spring.datasource.tomcat.url: jdbc:oracle:thin:@//orahost.com:1540/kubedb
  spring.datasource.tomcat.username: ${kube.datasource.oracle.username}
  spring.datasource.tomcat.password: ${kube.datasource.oracle.password}
  spring.datasource.tomcat.validationQuery: select 1 from dual
  spring.datasource.tomcat.initialSize: "10"
  spring.datasource.tomcat.logAbandoned: "true"
  spring.datasource.tomcat.maxActive: "10"
  spring.datasource.tomcat.maxIdle: "10"
  spring.datasource.tomcat.minIdle: "10"
  spring.datasource.tomcat.removeAbandoned: "true"
  spring.datasource.tomcat.testOnBorrow: "true"
  spring.datasource.tomcat.testOnConnect: "true"
  spring.datasource.tomcat.testOnReturn: "true"
  spring.datasource.tomcat.testWhileIdle: "true"
  spring.datasource.tomcat.timeBetweenEvictionRunsMillis: "3600000"
  spring.datasource.tomcat.validationQueryTimeout: "60"

