apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T17:58:13Z"
  name: kube-es-config
  namespace: kube-green
  resourceVersion: "19400"
  uid: 0cbd2ac8-97a6-45ff-9bd0-3fa61e22ec32
data:
  spring.data.elasticsearch.rest.uri: http://eshost.com:9200
  spring.data.elasticsearch.rest.username: ${kube.datasource.elasticsearch.username}
  spring.data.elasticsearch.rest.password: ${kube.datasource.elasticsearch.password}
  es.index-name.summary: kube-dev
  es.docType: _doc
  spring.data.elasticsearch.rest.sockettimeout: "60000"
  spring.data.elasticsearch.rest.connecttimeout: "30000"
